### PR TITLE
Unit tests for API Client

### LINKED ISSUE #16: Write tests for Client
In #15, unit tests for basic usage of `RequestPayload`, `ResponsePayload`, and `Token` were written.

We should also have a test for `Client` and its `verify` method.

For these tests, maybe we could use the [`responses`](https://github.com/getsentry/responses#basics) package to mock the verifying server.

### PR DESCRIPTION
**Pull request by angela-tran**
Closes #16 

### Summary
This PR sets up pytest for this project and adds unit tests for the `client` module.
Dependencies such as server responses or the `RequestToken`/`ResponseToken` classes are mocked so that these tests are really only testing units within the `client` module.

There is some overlap here with the tests that were written in cal-itp/benefits#575. Those tests were meant to check for regressions as this package was being iterated on.

### Reviewing this PR
You can run the tests with VS Code's Testing panel. Another way to run them is `cd tests` and then `./run.sh` --  a coverage report will be generated in `src/tests/coverage` when running with this script.

### CODE REVIEW

**Comment by angela-tran** [comment]
Current output when running `pytest` locally with coverage:
```
calitp@ef410b64dc1e:~/src/tests$ ./run.sh 
==================================================================== test session starts =====================================================================
platform linux -- Python 3.9.13, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/calitp/src/tests
plugins: cov-3.0.0, mock-3.7.0
collected 16 items                                                                                                                                           

test_client.py ................                                                                                                                        [100%]

---------- coverage: platform linux, python 3.9.13-final-0 -----------
Name                                           Stmts   Miss Branch BrPart  Cover
--------------------------------------------------------------------------------
/home/calitp/src/eligibility_api/__init__.py       0      0      0      0   100%
/home/calitp/src/eligibility_api/client.py        54      2     17      0    97%
/home/calitp/src/eligibility_api/server.py        29     29      0      0     0%
/home/calitp/src/eligibility_api/tokens.py        69     52     14      0    28%
--------------------------------------------------------------------------------
TOTAL                                            152     83     31      0    50%


===================================================================== 16 passed in 0.80s =====================================================================
Wrote HTML report to coverage/index.html
```   
The line of interest here being:
```
/home/calitp/src/eligibility_api/client.py        54      2     17      0    97%
```

**Comment by angela-tran** [comment]
I think it can be a separate pull request to set up GitHub workflows for
 - running these tests in CI
 - publishing the coverage report to the eligibility-api docs site

**Comment by angela-tran** [comment]
Some feedback to incorporate: add a comment for tests that are just expecting to not have an exception thrown.

**Comment by angela-tran** [comment]
I've added the comments we talked about, so this is ready for re-review! 

Let me know if for whatever reason the comments are not what you expected or there was code I should've removed. 🙏

**Review by thekaveman — APPROVED** [review]
Won't block since this looks good, but 2 points of feedback:

* I would remove the `_test` prefix from the helper functions that provide data, since that is so close to the convention for actual test functions
* I would actually expect the helpers to come _first_ in the file, then used/referenced later by the tests 🤷

**Pull request merged**
